### ISSUE TITLE
Allow downloading a tab delimited file with the taxonomy summary

### ISSUE THREAD

**Issue by josenavas** [qiita-spots/qp-qiime2#17]
QIIME2 stores it in a JSON format. Users often want to plot the taxonomy in their favorite plotting system.

@tkosciol Is there anything missing here?

**Comment by tkosciolek** [comment]
That's pretty accurate.
So, as I understand the solution would be to save `json` as a `tsv`.

**Comment by antgonza** [comment]
Closing as storing and allowing to download the qza/qvz provides this functionality.
